[package]
name = "launcher"
version = "0.1.0"
authors = ["Michael van Niekerk <mvniekerk@gmail.com>"]
edition = "2018"

[dependencies]
gio = "0.14"

[dependencies.gtk]
version = "0.14"
features = ["v3_22"]
