[package]
name = "launcher"
version = "0.1.0"
authors = ["Michael van Niekerk <mvniekerk@gmail.com>"]
edition = "2018"

[dependencies]
gio = "^0"

[dependencies.gtk]
version = "0.6.0"
features = ["v3_20"]
